# Write your MySQL query statement below

# SELECT MAX(SALARY) FROM EMPLOYEE AS 'SecondHighestSalary' WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE)

SELECT MAX(SALARY) as 'SecondHighestSalary' FROM EMPLOYEE WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE)

